apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: stupid-meta-name
spec:
  name: stupid-spec-name
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: whitelilis/docker_sklearn
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
      parameters:
        - name: fix
          type: INT
          value: "55"
    name: stupdi-predict-name
    replicas: 1
